// AUTO-GENERATED by Sentinel — do not edit manually
// Suite: Test
// Re-generated on every push. Edit cases via the Sentinel dashboard.

export interface SuiteCaseResult {
  caseId: string;
  endpointKey: string;
  testcaseId: string;
  status: 'pass' | 'fail' | 'error';
  httpStatus: number | null;
  durationMs: number;
  error?: string;
}

export async function run(context: {
  baseUrl: string;
  authToken: string;
  workspaceId?: string;
  fetchImpl?: typeof fetch;
}): Promise<SuiteCaseResult[]> {
  const results: SuiteCaseResult[] = [];

  // case 1: GET /hub/communication-v2/api/centrifugo/token
  {
    const { run: runCase0 } = await import('../../modules/communication-v2/GET__hub_communication-v2_api_centrifugo_token/run-function');
    try {
      const r = await runCase0({ ...context, testcaseId: '6d7736bc-737d-498e-aebb-9a9b6bd9a221' });
      results.push({ caseId: 'be436b63-64ba-4f94-bfcf-3e3e0bc4e375:6d7736bc-737d-498e-aebb-9a9b6bd9a221:v2', endpointKey: 'GET /hub/communication-v2/api/centrifugo/token', testcaseId: '6d7736bc-737d-498e-aebb-9a9b6bd9a221', status: 'pass', httpStatus: r.status, durationMs: r.durationMs });
    } catch (err) {
      results.push({ caseId: 'be436b63-64ba-4f94-bfcf-3e3e0bc4e375:6d7736bc-737d-498e-aebb-9a9b6bd9a221:v2', endpointKey: 'GET /hub/communication-v2/api/centrifugo/token', testcaseId: '6d7736bc-737d-498e-aebb-9a9b6bd9a221', status: 'error', httpStatus: null, durationMs: 0, error: String(err) });
    }
  }

  // case 2: GET /configsettings/config
  {
    const { run: runCase1 } = await import('../../modules/config/GET__configsettings_config/run-function');
    try {
      const r = await runCase1({ ...context, testcaseId: '22b1f02e-e8a2-4f32-b1ff-b5d5ec2dcc29' });
      results.push({ caseId: 'be436b63-64ba-4f94-bfcf-3e3e0bc4e375:22b1f02e-e8a2-4f32-b1ff-b5d5ec2dcc29:v2', endpointKey: 'GET /configsettings/config', testcaseId: '22b1f02e-e8a2-4f32-b1ff-b5d5ec2dcc29', status: 'pass', httpStatus: r.status, durationMs: r.durationMs });
    } catch (err) {
      results.push({ caseId: 'be436b63-64ba-4f94-bfcf-3e3e0bc4e375:22b1f02e-e8a2-4f32-b1ff-b5d5ec2dcc29:v2', endpointKey: 'GET /configsettings/config', testcaseId: '22b1f02e-e8a2-4f32-b1ff-b5d5ec2dcc29', status: 'error', httpStatus: null, durationMs: 0, error: String(err) });
    }
  }

  return results;
}
